name: Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up BPF toolchain
      run: |
        sudo apt update
        sudo apt install -y llvm clang libbpf-dev libc6-dev libc6-dev-i386 linux-headers-$(uname -r)
        sudo ln -sf /usr/include/$(uname -m)-linux-gnu/asm /usr/include/asm
        sudo ln -sf /usr/include/$(uname -m)-linux-gnu/bits /usr/include/bits
        sudo ln -sf /usr/include/$(uname -m)-linux-gnu/gnu /usr/include/gnu
        sudo ln -sf /usr/include/$(uname -m)-linux-gnu/sys /usr/include/sys

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    - name: Compile BPF programs
      run: go generate ./...

    - name: Build
      run: go build ./...

    - name: Run tests
      run: sudo -E go test -v ./...
